---
title: "Homework 1"
author: "Your name"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Due: 2/4/2019 before 11pm. Submit in Canvas (file upload). Rmd file and the html output file (submit both files) are strongly recommended, but not required.

1. (10 pts) Let $X = (X_{1}, \ldots, X_{n})'$ be the $n \times p$ data matrix, where $X_{i} = (X_{i1}, \ldots, X_{ip})'$ is the $i$th onservation. Let $\bar{X} = n^{-1} \sum_{i = 1}^{n} X_{i}$ be the sample mean. Let $s_{j_1j_2} = n^{-1} \sum_{i = 1}^{n} (X_{ij_1} - \bar{X}_{j_1})(X_{ij_2} - \bar{X}_{j_2})$ be the sample covariance between the $j_1$th and $j_2$th variables. Let $S = (s_{j_1j_2})$ be the sample covariance matrix.
Show that $$S = \frac{1}{n}X' X - \bar{X}' \bar{X}.$$
<br>

2. (10 pts) Find ALL the eigenvalues and their eigenvectors for the following matrices

    - $\Sigma = \sigma \mathbb{1} \mathbb{1}'$ where $\mathbb{1} = (1, 1, \ldots, 1)'$ is the $p$ dimensional vector of 1.
    - $\Sigma = \mbox{diag}(\sigma_{1}, \ldots, \sigma_{p})$ is a diagonal matrix. 
 <br> <br>

3. (10 pts) Show that $\mbox{tr}(AB) = \mbox{tr}(BA)$. 
<br> <br>

4. (10 pts) Given two variables in the data matrix X (say the $j_1$th and $j_2$th variables). Show that their sample correlation will not change by standardization.
<br> <br>

5. (10 pts) Given a data matrix $X$ as in Question 2. Assume the means of the $p$ variables are zero. Let $S = \frac{1}{n}X' X$ be the sample covariance matrix. Let $\lambda_{1} \geq \lambda_{2} \geq \ldots \geq \lambda_{p}$ be the ordered eigenvalues of $S$. Let $e_{1}, \ldots, e_{p}$ be their corresponding orthogonal eigenvectors with unit length.
In multivariate analysis, we usually want to use the first few eigenvalues and eigenvectors to represent the original data, as a tool of dimension reduction. 

    - On one aspect, let $$S_{m} = \lambda_{1}e_{1}e_{1}' + \ldots + \lambda_{m}e_{m}e_{m}'$$ be an approximate of $S$ for $m < p$. Calculate $\mbox{tr}\{(S - S_{m})^{2}\}$ and $\mbox{tr}\{(S - S_{m})^{2}\} / \mbox{tr}(S^{2})$, where $\mbox{tr}(S^{2})$ can be regarded as the total variation of the data.
    - On another aspect, $\{Xe_{1}, \ldots, Xe_{m}\}$ are the transformed data by the eigenvectors. Calculate the sample covariance $S_{t}$ of $\{Xe_{1}, \ldots, Xe_{m}\}$ (regard the sample mean as 0). What is $\mbox{tr}(S_{t}^{2})$ comparing to $\mbox{tr}(S^{2})$?
    - What can you conclude on the dimension reduction by eigenvectors from the above two points?
<br> <br>

6. (10 pts) Use the **ggplot2** package to visualize the data `iris` in R.

    - Make a scatter plot for the variables `Sepal.Length` and `Sepal.Width` colored by `Species`. What can you see?
    - Make a scatter matrix for every pairs of the variables, colored by `Species`. What can you see?
    - Calculate the sample mean for each species.
    - Make a star plot for the sample means of each species to illustrate their potential differences. Comment.
<br> <br>